M48
; DRILL file {KiCad (6.0.6)} date sön 26 jun 2022 20:43:02
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-26T20:43:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.8858Y-1.6142
X5.8858Y-2.7953
X6.6535Y-1.6142
X6.6535Y-2.7953
T0
M30
